### PR TITLE
Anoncoin version 0.8.5.2

### PR DESCRIPTION
**Pull request by meeh420**
Upgraded the code and applied a bunch of patches from the Bitcoin source.

### CODE REVIEW

**Comment by meeh420** [comment]
Added debian files to the pull request.

**Comment by BroTroxer** [comment]
ACK

**Comment by meeh420** [comment]
Updated some more minor fixes in the client.

Also rewrote the I2P seed process. This will make let i2p=1 prio I2P nodes, and only connect to clearnet nodes if it finds too few I2P nodes or they has reached the maximum limit of connections.

Found and fixed a memory leak reported by valgrind.

**Comment by BroTroxer** [comment]
ACK

**Comment by yhaenggi** [comment]
ACK

**Pull request merged**
