### PR TITLE
Develop

### PR DESCRIPTION
**Pull request by mrebum**
Embed default qss stylesheet

### CODE REVIEW

**Comment by lunokhod** [comment]
Here are a few remaining problems (commit edc3b6f).
1. The "(default)" theme still corresponds to the purple "Anoncoin" theme. Choosing default, and clicking ok does not bring back the old "bitcoin" style wallet.
2. Clicking on the "Address book" and "Accounts" tab opens a new window, as opposed to displaying this information in the main wallet.
3. Ordering of wallet tabs: I think it would be best to use Overview, Accounts, Send, Receive, Transactions, Address Book.
4. Units tab in bottom left hand corner. In addition to ANC, mANC, microANC, maybe we should add "Satoshis", which is 10^-8, the small indivisible unit possible.
5. I would love to get rid of the "About Qt" menu item. Are we legally required to show this? Or is acknowledging this in the source somewhere good enough?

**Comment by mrebum** [comment]
1. This pulls the "Anoncoin" theme back out to a separate theme and lets "(default)" specify no theme (i.e. bitcoin style).
2. Accounts and Addresses are now inside the main window.  Themes adjusted to show the Transactions frame the same color as the other frames.
3. Tabs reordered.
4. To me, a satoshi is a bitcoin unit.  But I know it is starting to mean 10^-8 everywhere.  Confusing.  Nonetheless, I'll be happy to change it.  May I suggest using "Satoshis" in text and "sANC" in abbreviations?
5. I do not know the multinational legalities involved.  We probably need to leave it in somewhere.  Maybe move it to a button on the About Anoncoin page?

**Comment by lunokhod** [comment]
I noticed two small bugs.

First, every time I go to the accounts window, my list of addresses is re-added to the list that is already displayed. For example, if I have three addresses, the first time I go to the "accounts" pane I see three. The second time I click on this, the addresses are doubled, and there are 6 (two for each), and the third 
time there are 3 sets...

Second, for the themes pull down selection menu, the "(default)" theme shows up as a blank entry. When you click on the menu, it then does show the name "(default)". See the attached screen shot.

Third, in this is minor too, but it would probably be good to have a "total" on the "accounts" pane, similar to the overview page.

Lastly, for the accounts, I am curious how change addresses show up and are grouped. It would be best if they were grouped similar to how they are in coin control.

screen shot 2015-06-13 at 10 00 15

screen shot 2015-06-13 at 10 03 52

**Comment by mrebum** [comment]
The accounts page uses the existing method "GetAddressBalances()" from wallet.cpp.  It is what "listaddressgroupings" uses.

**Pull request closed without merging**
