### PR TITLE
Working QT client build, with alternative language support....and more read below

### PR DESCRIPTION
**Pull request by GroundRod**
Primary purpose of this update is to release source that will allow you to interact with optional languages when building and using Anoncoin-QT.  We now also have all the Transifex support machinery defined and working with these changes.

Many edits and hours getting that working right, plus fast work by our team on Transifex, allowed an initial language package to be included in this release..  

Included a very early start on a possible alternative difficulty algo, we may soon move away from the KGW algo and hard fork the chain. 

Our contrib/anoncoin-qt.pro file is used by the platform builder software, when creating a new master English file to be submitted when source code or QT forms change and warrants translation updates be done on Transifex.  A recent small edit to this file, caused a merge conflict for me, as I had updated and corrected it for that use.  

Additionally the latest upstream merge for me cause two other deleted file problems, in the doc/ folder, both are important & have now been restored & edited for content, see the details below:

The README_windows.txt is used when constructing a windows setup.exe deployment package, it can be edited at any time, but not deleted.  The other bootstrap.md file will soon become important as it explains how to find/download & install the bootstrap.dat file.  Soon  to be released for Anoncoin, a bootstrap.dat file can offer the user and extremely fast blockchain setup and go install.  Recent python software edits and configuration files have been setup, testing is underway and that work is found in the contrib/linearize folder.

Small change to the text strings returned for peertable node display should now indicate what network service bits 2 and 7 are, aka 2) node supports BLOOM filters and 7) the node is capable of I2P network communications service.

Additionally a change was introduced here, that IF there is no anoncoin.conf file and no command line parameter disabling I2P, the software will start out and attempt to connect in onlynet=i2p mode, with default parameters.  This needs to be tested, and confirmed that we want this behavior for new installs.

Probably more, but that brings things up to a little more current condition.  We will soon will be starting Pre-release build #4....

GR

### CODE REVIEW

**Comment by lunokhod** [comment]
1. Fonts work fine on OS 10.9, however, I haven't checked on 10.10 (don't have this installed on any of my machines yet).
2. If the default behavior is to connect to I2P, that is fine: but, what happens if the I2P router isn't started? In my opinion, until we have a built in i2pd router, if nothing else works, the client should connect by clearnet.

**Comment by GroundRod** [comment]
Thanks on the fonts feedback, was concerned that I had broken something in your builds.

As to the initial I2P connect behavior, Please you and CS talk this over.  And let me know.  

FWIW I agree with you...

My testing shows it works here, it first comes up and shows the Running on Clearnet warning.  For most people, it will then exit and what is left displayed on the users console are those few message errors remaining as output, because of the I2PSAM session creation failures.

In my case, I've indexed the blockchain, as required for mutisig transaction testing, having set the txindex=1 in my normally used anoncoin.conf file.    So in addition to the Clearnet warning, it asks me, if I want to now reindex the blockchain, because that option was not found to be set.  It allows me to click ok or abort, so once I abort, it exits as one would expect.  I had simply renamed the file, for this test.

Will test tonight if the program starts up properly with default values and connects when the router is available.  I can then comment the code out, or leave it in, whatever you two decide.....

**Comment by GroundRod** [comment]
BTW...these couple of lines of code needed, are in the section where we are about to attempt to write a brand new, first time use anoncoin.conf file (aka WriteFirstConfig()).  An issue, I've not yet had time to get back to.  Default values for everything that can be in one of those needs to be defined.  My anoncoin.conf.sample file in the doc/ folder is now an attempt to do that.  Some are there as only to be informative and will have a leading # in front of the parameter.  Others are not commented out in the sample, and would be the values I'll intend to write directly into the first config file, when I get back to that project.  At the moment I have onlynet=i2p  set as one of those defined.

So please consider also going over all our settings, and deciding which ones need to be written on a FirstConfigFile, and what value they should be set at.

**Comment by Cryptoslave** [comment]
I was thinking i2pd is too much buggy to use it for next release. We will see how it will be for release of myriad 3chain but until it is not buggy we cannot use a i2plib embedded in the client. 

So well maybe in the default anoncoin.conf we put onlynet=i2p and dyn, but if no anoncoin.conf we connect clearnet after the warning. Shall leave this warning because in this way ppl are obliged to setup anoncoin.conf to remove the damn box.

**Comment by GroundRod** [comment]
I turned off the code by commenting it out for now, it no longer forces i2p, plus it makes testing various things a real pain, working on testnet/regtest operation now....sometimes there has been no data folder or configure file to start with...

**Comment by GroundRod** [comment]
Without my code change, protocol service bit #2, shows up as an 'unknown service' in our PeerTable entries, because most (if not all) nodes on our network are advertising it set.

The technology came out about the same time as our original v8 technology wallet, thus it had the support, my current understanding anyway.  That is why it is being seen and shown to us in the v9 node entry details.  How our new software is handling support of it, is important to understand, as well as the other 2 bits that are showing up as set.  NETWORK and I2PNET, the later being something Meeh invented, which I've tried my best to port to v9, yet still have many hours of work to get done, before I would call that working really well.

On BLOOM filters....here is some links and ideas to consider:
Read this document, at least starting at the section called Specification:
http://sourceforge.net/p/bitcoin/mailman/message/31298904/
After that section, is one called Design rational.  This is the last sentence from that paragraph "Note how in this example DoS attacks are made prohibitively expensive by the work required to create a valid block header."

Bloom filers definitely help with security, and apparently we have lots of nodes operating on a network which are broadcasting support of it, as protocol bit #2 is coming in set for everyone I've looked at.   BIP37 is all about this topic.
https://github.com/bitcoin/bips/blob/master/bip-0037.mediawiki
After that lite reading, try: http://en.wikipedia.org/wiki/Bloom_filter 

About then, is when I decided I have no idea if this is working, or how to test it, open to ideas.  Our v9 code is passing a basic low level Bloom filter test, that is about all I know.  Reading this helped me allot though:
http://chimera.labs.oreilly.com/books/1234000001802/ch06.html#_bloom_filters

Basically at this point I'm of the opinion that when/if Anoncoin starts having SPV peers show up on the network, those lite-weight wallets will create bloom filter requests to hide what addresses in transactions they are really looking for, full nodes, capable of BLOOM protocol, will be able to respond to that request, as the SPV peer does not have a complete copy of the blockchain, this protects them from snoopers trying to find what addresses they have in their wallet, but I am not the best person to document this.

I sure can drop that displayed item, call it something else, or let it revert back to Unknown Service(x02).  Perhaps the best idea is to just documentation it as is, and allot of other stuff related to the PeerTable display in a new wiki page: Understanding the PeerTable
Then by the time I get the part of our QT interface code working better, we can all refer to that wiki page, as a place to understand what all the data really means...

**Pull request merged**
