### PR TITLE
Initial anoncoin conversion and builder system upgrade

### PR DESCRIPTION
**Pull request by GroundRod**
First round of upgrade history

### CODE REVIEW

**Comment by GroundRod** [comment]
My local working branch is now equal the commit history.  Build #1 is tagged as v0.9.4.1, and has been out for several days, testing results have proven very positive.  Forget to mention allot of details, one that comes to mind is on commit Phase III, where LevelDB was upgraded to v1.18.

**Comment by GroundRod** [comment]
Note on the file main2.cpp 
This is the code that keeps constantly changing, as anoncoin's nature is not the same as any other coin and it's diffuculty algo is about to be changed, I've moved those aspects out of main.cpp and into their own file., hunting for it all the time, buried in main.cpp is a pain.  Atm it is included 'inline'  from within main.cpp to compile with.  Bad programming pratice, I know, it's a temporary solution & still considering my options as to where to keep it or put it back after we've updated our difficulty calc algo and implemented support for the merged mining attributes we're expecting as proof of work.

**Comment by yhaenggi** [comment]
why did you remove the .git\* files? i didnt check further...

**Comment by GroundRod** [comment]
@K1773R references to litecoin stuff, objs that are no longer built with these names &/or in the same place.  Working on generating new ones, will update the repo with something that better refects the current build process....  

While doing these commits, it became increasingly unclear as to wither or not it was going to include all the specific files I was trying to submit for version control.  At one point it included a Makefile.in, that should NOT have been included, think I had to amend that commit, before posting.  The .gitmodule/attribute declare was trying to build a substutition string into the version.cpp file, which no longer exists...  So starting over pretty much, left several in various places...

**Comment by mikalv** [comment]
Awesome. Love you GroundRod <3 haha. Accepted!

**Comment by GroundRod** [comment]
back at U, onward with more fixes...

**Pull request merged**
